#!/bin/bash

DEVICE_DIR=/storage/emulated/0/Android/data/com.github.murzagalin.snapshot_testing/files/Pictures/.
SCREENSHOTS_DIR="$1"

rm -rf $SCREENSHOTS_DIR
mkdir -p $SCREENSHOTS_DIR
./gradlew clean installDebug installDebugAndroidTest

adb shell settings put global window_animation_scale 0.0
adb shell settings put global transition_animation_scale 0.0
adb shell settings put global animator_duration_scale 0.0

# to find list of instrumentations run: adb shell pm list instrumentation
adb shell am instrument -w -m  \
-e class 'com.github.murzagalin.snapshot_testing.views.ScreenshotsMaker' \
com.github.murzagalin.snapshot_testing.test/androidx.test.runner.AndroidJUnitRunner
adb pull $DEVICE_DIR. $SCREENSHOTS_DIR
adb shell rm -r $DEVICE_DIR

# adb shell am instrument -w -m  -e class 'com.github.murzagalin.snapshot_testing.ScreenshotsMaker' com.github.murzagalin.snapshot_testing.test/androidx.test.runner.AndroidJUnitRunner